server:
    port: 9066
    servlet:
      context-path: /at

security:
  oauth2:
    resource:
      jwt:
        keyValue: |
                    -----BEGIN PUBLIC KEY-----
                    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhiiifKv6Otf5PyqIE+LQ
                    EiJRRh6q8piPY9Okq+RfRu9Bue0D8hq7aFxcgkLZ6Bg9CAS+w1KdaE5MMeOCVVxv
                    rpRETzVpAsh6GL5nBc679jSqMzjr3V4uty46ilL4VHKSxlZh5Nmz5EMHPI5iwpNs
                    8U5n3QiwsTk514FXad54xPSPH3i/pDzGSZHrVcwDVaOKn7gFiIqP86vkJB47JZv8
                    T6P5RK7Rj06zoG45DMGWG3DQv6o1/Jm4IJQWj0AUD3bSHqzXkPr7qyMYvkE4kyMH
                    6aVAsAYMxilZFlJMv2b8N883gdi3LEeOJo8zZr5IWyyROfepdeOL7UkAXddAj+dL
                    WQIDAQAB
                    -----END PUBLIC KEY-----

jwt:
  certificate:
    store:
      file: classpath:/certificate/mykeystore.jks
      password: abirkhan04
    key:
      alias: myauthkey
      password: abirkhan04

spring:
  application:
    name: mirc-server-auth
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    cache: false
#    servlet:
#      content-type: text/html
  cloud:
      consul:
        host: 192.168.141.132
        port: 8500
        discovery:
#          healthCheckPath: /at/actuator/health
          healthCheckInterval: 15s
          instance-id: ${spring.application.name}-${server.port}
#          ip-address:
          health-check-url: http://192.168.141.132:9066/at/actuator/health
#          register: true
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: false
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://192.168.1.123:3306/bgbc?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useServerPrepStmts=true&rewriteBatchedStatements=true
    username: game
    password: game
    driver-class-name: com.mysql.jdbc.Driver
#security:
#  oauth2:
#    resource:
#      token-info-uri: http://localhost:9066/user
#logging.level.org.springframework.security: debug